import { Product } from './store';
import { getPlaceholderImage, getRandomImage } from './utils';

export const products: Product[] = [
  {
    id: '1',
    name: 'Royal Oud',
    description: 'A luxurious blend of rare oud wood, amber, and musk creating an opulent and mysterious fragrance.',
    price: 299.99,
    image: getPlaceholderImage(0),
    images: [getPlaceholderImage(0), getPlaceholderImage(1), getPlaceholderImage(0)],
    category: 'Woody',
    fragranceType: 'Oriental',
    fragranceNotes: ['Oud', 'Amber', 'Musk', 'Sandalwood'],
    rating: 4.8,
    reviewsCount: 127,
    inStock: true,
    size: '50ml',
  },
  {
    id: '2',
    name: 'Arabian Nights',
    description: 'An exotic composition of rose, jasmine, and saffron with a base of vanilla and oud.',
    price: 249.99,
    image: getPlaceholderImage(1),
    images: [getPlaceholderImage(1), getPlaceholderImage(0)],
    category: 'Floral',
    fragranceType: 'Floral Oriental',
    fragranceNotes: ['Rose', 'Jasmine', 'Saffron', 'Vanilla', 'Oud'],
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
    size: '50ml',
  },
  {
    id: '3',
    name: 'Desert Bloom',
    description: 'Fresh and vibrant with notes of citrus, mint, and lavender, finished with white musk.',
    price: 179.99,
    image: getPlaceholderImage(2),
    images: [getPlaceholderImage(2)],
    category: 'Fresh',
    fragranceType: 'Fresh',
    fragranceNotes: ['Citrus', 'Mint', 'Lavender', 'White Musk'],
    rating: 4.5,
    reviewsCount: 156,
    inStock: true,
    size: '50ml',
  },
  {
    id: '4',
    name: 'Amber Essence',
    description: 'Rich amber with hints of vanilla, tonka bean, and a touch of spice for warmth.',
    price: 269.99,
    image: getPlaceholderImage(3),
    images: [getPlaceholderImage(3)],
    category: 'Woody',
    fragranceType: 'Oriental',
    fragranceNotes: ['Amber', 'Vanilla', 'Tonka Bean', 'Spice'],
    rating: 4.9,
    reviewsCount: 203,
    inStock: true,
    size: '50ml',
  },
  {
    id: '5',
    name: 'Rose Petals',
    description: 'Delicate Bulgarian rose with peony and white flowers, wrapped in soft musk.',
    price: 199.99,
    image: getPlaceholderImage(4),
    images: [getPlaceholderImage(4)],
    category: 'Floral',
    fragranceType: 'Floral',
    fragranceNotes: ['Bulgarian Rose', 'Peony', 'White Flowers', 'Musk'],
    rating: 4.6,
    reviewsCount: 94,
    inStock: true,
    size: '50ml',
  },
  {
    id: '6',
    name: 'Saffron Gold',
    description: 'Premium saffron infused with oud and amber, creating an unforgettable luxury scent.',
    price: 349.99,
    image: getPlaceholderImage(5),
    images: [getPlaceholderImage(5)],
    category: 'Woody',
    fragranceType: 'Oriental',
    fragranceNotes: ['Saffron', 'Oud', 'Amber', 'Patchouli'],
    rating: 4.9,
    reviewsCount: 178,
    inStock: true,
    size: '50ml',
  },
  {
    id: '7',
    name: 'Musk Heritage',
    description: 'Pure white musk with sandalwood and a hint of lavender for a classic timeless fragrance.',
    price: 159.99,
    image: getPlaceholderImage(6),
    images: [getPlaceholderImage(6)],
    category: 'Woody',
    fragranceType: 'Woody',
    fragranceNotes: ['White Musk', 'Sandalwood', 'Lavender'],
    rating: 4.4,
    reviewsCount: 112,
    inStock: true,
    size: '50ml',
  },
  {
    id: '8',
    name: 'Jasmine Dreams',
    description: 'Enchanting jasmine with gardenia and tuberose, finished with sweet vanilla.',
    price: 219.99,
    image: getPlaceholderImage(7),
    images: [getPlaceholderImage(7)],
    category: 'Floral',
    fragranceType: 'Floral',
    fragranceNotes: ['Jasmine', 'Gardenia', 'Tuberose', 'Vanilla'],
    rating: 4.7,
    reviewsCount: 145,
    inStock: true,
    size: '50ml',
  },
  {
    id: '9',
    name: 'Ocean Breeze',
    description: 'Crisp aquatic notes with sea salt, bergamot, and marine accord for a refreshing experience.',
    price: 189.99,
    image: getPlaceholderImage(8),
    images: [getPlaceholderImage(8)],
    category: 'Fresh',
    fragranceType: 'Fresh',
    fragranceNotes: ['Sea Salt', 'Bergamot', 'Marine Accord', 'Vetiver'],
    rating: 4.5,
    reviewsCount: 98,
    inStock: true,
    size: '50ml',
  },
  {
    id: '10',
    name: 'Velvet Oud',
    description: 'Silky smooth oud with rose and saffron, creating an opulent and sophisticated blend.',
    price: 319.99,
    image: getPlaceholderImage(9),
    images: [getPlaceholderImage(9)],
    category: 'Woody',
    fragranceType: 'Oriental',
    fragranceNotes: ['Oud', 'Rose', 'Saffron', 'Amber'],
    rating: 4.8,
    reviewsCount: 167,
    inStock: true,
    size: '50ml',
  },
  {
    id: '11',
    name: 'Lily Garden',
    description: 'Pure white lily with magnolia and freesia, creating a fresh and elegant floral bouquet.',
    price: 199.99,
    image: getPlaceholderImage(10),
    images: [getPlaceholderImage(10)],
    category: 'Floral',
    fragranceType: 'Floral',
    fragranceNotes: ['White Lily', 'Magnolia', 'Freesia', 'Green Leaves'],
    rating: 4.6,
    reviewsCount: 76,
    inStock: true,
    size: '50ml',
  },
  {
    id: '12',
    name: 'Citrus Zest',
    description: 'Vibrant mix of lemon, orange, and bergamot with a hint of mint for an energizing freshness.',
    price: 169.99,
    image: getPlaceholderImage(11),
    images: [getPlaceholderImage(11)],
    category: 'Fresh',
    fragranceType: 'Fresh',
    fragranceNotes: ['Lemon', 'Orange', 'Bergamot', 'Mint'],
    rating: 4.4,
    reviewsCount: 134,
    inStock: true,
    size: '50ml',
  },
];

export const categories = ['All', 'Woody', 'Floral', 'Fresh'];

export const fragranceTypes = ['All', 'Oriental', 'Floral', 'Floral Oriental', 'Woody', 'Fresh'];

export const testimonials = [
  {
    id: '1',
    name: 'Aisha Rahman',
    rating: 5,
    comment: 'Royal Oud is absolutely divine! The fragrance lasts all day and the quality is exceptional.',
    location: 'Dubai, UAE',
  },
  {
    id: '2',
    name: 'Mohammed Ali',
    rating: 5,
    comment: 'Best ittar collection I have ever purchased. Arabian Nights is my favorite - truly authentic.',
    location: 'London, UK',
  },
  {
    id: '3',
    name: 'Fatima Khan',
    rating: 5,
    comment: 'The packaging is beautiful and the scents are so luxurious. Highly recommend Saffron Gold!',
    location: 'Karachi, Pakistan',
  },
  {
    id: '4',
    name: 'Ahmed Hassan',
    rating: 5,
    comment: 'Premium quality at reasonable prices. Desert Bloom is perfect for daily wear.',
    location: 'Cairo, Egypt',
  },
];

export interface Review {
  id: string;
  productId: string;
  name: string;
  email: string;
  rating: number;
  comment: string;
  date: string;
}

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    name: 'Sarah Ahmed',
    email: 'sarah@example.com',
    rating: 5,
    comment: 'Absolutely love this! The oud is so authentic and long-lasting.',
    date: '2024-01-15',
  },
  {
    id: '2',
    productId: '1',
    name: 'Omar Hassan',
    email: 'omar@example.com',
    rating: 5,
    comment: 'Best purchase ever. The fragrance is exactly as described.',
    date: '2024-01-20',
  },
  {
    id: '3',
    productId: '2',
    name: 'Layla Mansour',
    email: 'layla@example.com',
    rating: 4,
    comment: 'Beautiful scent, very elegant. Would definitely buy again.',
    date: '2024-02-01',
  },
];

